trigger:
  batch: false
  branches:
    include:
      - peter-pdf-1

variables:
  - group: product-readiness.docfx
  - name: gitRepo
    value: Edgecmd-Docs

jobs:
  - job: Publish
    pool:
      name: 00-OSIManaged-Containers
      demands: AgentType -equals osimanagedagent
    steps:
      # - script: |
      #    choco install DocFX --version=2.56.2
      #  displayName: 'Install DocFX 2.56.2'

      - script: |
          echo.
          dir
          echo.
          echo.
          echo "*** Clone source ***"
          echo.
          mkdir source
          cd source
          git clone https://user:$(gitToken)@github.com/osisoft/$(gitRepo).git --recurse-submodules
          dir
          cd $(gitRepo)
          dir
          echo.
          echo "*** Run DocFX ***"
          echo.
          docfx.exe ./docfx.json
          echo.
          echo "*** Contents of _site ***"
          echo.
          dir "C:\source\Edgecmd-Docs\_site"
          echo.
          echo "Complete!"
          echo.
        workingDirectory: 'C:\'
        displayName: 'Publish DocFX'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'C:\source\Edgecmd-Docs\_site'
          ArtifactName: 'drop'
          publishLocation: 'Container'

#      - task: WindowsMachineFileCopy@2
#        inputs:
#          SourcePath: '$(Build.ArtifactStagingDirectory)\_site'
#          MachineNames: 'clguild01.dev.osisoft.int'
#          AdminUserName: 'osi\pyueh'
#          AdminPassword: '$(adminPassword)'
#          TargetPath: 'C:\inetpub\wwwroot\en\Edgecmd-Docs-PeterPdf1'

      - task: AzureFileCopy@4
        inputs:
          SourcePath: '$(Build.ArtifactStagingDirectory)'
          azureSubscription: 'PYueh-Visual Studio Enterprise Subscription(94e67d6d-a3e6-425f-b9af-16971682c94c)'
          Destination: 'AzureBlob'
          storage: 'petersandbox1'
          ContainerName: '$web'
          # BlobPrefix: 'en'
