trigger:
  batch: true
  branches:
    include:
      - peter-pdf-1

variables:
  - group: product-readiness.docfx
  - name: gitRepo
    value: Edgecmd-Docs

jobs:
  - job: Publish
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - script: |
          choco install DocFX
        displayName: 'Install DocFX'

      - script: |
          echo "Clone source"
          mkdir source
          cd source
          git clone https://user:$(gitToken)@github.com/osisoft/$(gitRepo).git --recurse-submodules
          dir
          cd $(gitRepo)
          dir

          echo "Run DocFX"
          docfx.exe ./docfx.json

          echo "Move output files"
          mv .\_site $(Build.ArtifactStagingDirectory)\_site
          git clean -fd

          echo "Complete!"
        workingDirectory: 'C:\'
        displayName: 'Publish DocFX'
